# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    http_method_override: false
    trusted_hosts: ~
    trusted_proxies: ~
    trusted_headers: ~
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        default_locale: fr
        timezone: 'Europe/Paris'
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
